version: '3.8'

services:
  web:
    build: .
    command: sh -c "uv run python manage.py migrate && uv run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-i0)s_$$l0dmi)+vt4+6xz*n2#9w4!#nr()d&7+_s#o1#72-ijn^
      - ALLOWED_HOSTS=localhost,127.0.0.1
    stdin_open: true
    tty: true
